**EDA ON DATASET**

In [1]:
# connecting with google drive

# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# all output should be presist

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
# importing lib and loding dataset

import pandas as pd

url = "https://raw.githubusercontent.com/sumedhcharjan/Sales_Pridiction_Model_Excal/main/dataset/dataset.csv"
df = pd.read_csv(url)

df.head()

,Product_Id,Product_Weight,Product_Sugar_Content,Product_Allocated_Area,Product_Type,Product_MRP,Store_Id,Store_Establishment_Year,Store_Size,Store_Location_City_Type,Store_Type,Product_Store_Sales_Total
0,FD6114,12.66,Low Sugar,0.027,Frozen Foods,117.08,OUT004,2009,Medium,Tier 2,Supermarket Type2,2842.40
1,FD7839,16.54,Low Sugar,0.144,Dairy,171.43,OUT003,1999,Medium,Tier 1,Departmental Store,4830.02
2,FD5075,14.28,Regular,0.031,Canned,162.08,OUT001,1987,High,Tier 2,Supermarket Type1,4130.16
3,FD8233,12.10,Low Sugar,0.112,Baking Goods,186.31,OUT001,1987,High,Tier 2,Supermarket Type1,4132.18
4,NC1180,9.57,No Sugar,0.010,Health and Hygiene,123.67,OUT002,1998,Small,Tier 3,Food Mart,2279.36

In [5]:
# understanding structure

df.shape
df.columns
df.info()
df.dtypes

(8763, 12)

Index(['Product_Id', 'Product_Weight', 'Product_Sugar_Content',
       'Product_Allocated_Area', 'Product_Type', 'Product_MRP', 'Store_Id',
       'Store_Establishment_Year', 'Store_Size', 'Store_Location_City_Type',
       'Store_Type', 'Product_Store_Sales_Total'],
      dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Product_Id                 8763 non-null   object
 1   Product_Weight             8763 non-null   float64
 2   Product_Sugar_Content      8763 non-null   object
 3   Product_Allocated_Area     8763 non-null   float64
 4   Product_Type               8763 non-null   object
 5   Product_MRP                8763 non-null   float64
 6   Store_Id                   8763 non-null   object
 7   Store_Establishment_Year   8763 non-null   int64
 8   Store_Size                 8763 non-null   object
 9   Store_Location_City_Type   8763 non-null   object
 10  Store_Type                 8763 non-null   object
 11  Product_Store_Sales_Total  8763 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 821.7+ KB

Product_Id                    object
Product_Weight               float64
Product_Sugar_Content         object
Product_Allocated_Area       float64
Product_Type                  object
Product_MRP                  float64
Store_Id                      object
Store_Establishment_Year       int64
Store_Size                    object
Store_Location_City_Type      object
Store_Type                    object
Product_Store_Sales_Total    float64
dtype: object

In [ ]:
# breif discription of database

df.describe(include='all')
df.describe(include='object')

,Product_Id,Product_Weight,Product_Sugar_Content,Product_Allocated_Area,Product_Type,Product_MRP,Store_Id,Store_Establishment_Year,Store_Size,Store_Location_City_Type,Store_Type,Product_Store_Sales_Total
count,8763,8763.000000,8763,8763.000000,8763,8763.000000,8763,8763.000000,8763,8763,8763,8763.000000
unique,8763,NaN,4,NaN,16,NaN,4,NaN,3,3,4,NaN
top,FD306,NaN,Low Sugar,NaN,Fruits and Vegetables,NaN,OUT004,NaN,Medium,Tier 2,Supermarket Type2,NaN
freq,1,NaN,4885,NaN,1249,NaN,4676,NaN,6025,6262,4676,NaN
mean,NaN,12.653792,NaN,0.068786,NaN,147.032539,NaN,2002.032751,NaN,NaN,NaN,3464.003640
std,NaN,2.217320,NaN,0.048204,NaN,30.694110,NaN,8.388381,NaN,NaN,NaN,1065.630494
min,NaN,4.000000,NaN,0.004000,NaN,31.000000,NaN,1987.000000,NaN,NaN,NaN,33.000000
25%,NaN,11.150000,NaN,0.031000,NaN,126.160000,NaN,1998.000000,NaN,NaN,NaN,2761.715000
50%,NaN,12.660000,NaN,0.056000,NaN,146.740000,NaN,2009.000000,NaN,NaN,NaN,3452.340000
75%,NaN,14.180000,NaN,0.096000,NaN,167.585000,NaN,2009.000000,NaN,NaN,NaN,4145.165000
max,NaN,22.000000,NaN,0.298000,NaN,266.000000,NaN,2009.000000,NaN,NaN,NaN,8000.000000

,Product_Id,Product_Sugar_Content,Product_Type,Store_Id,Store_Size,Store_Location_City_Type,Store_Type
count,8763,8763,8763,8763,8763,8763,8763
unique,8763,4,16,4,3,3,4
top,FD306,Low Sugar,Fruits and Vegetables,OUT004,Medium,Tier 2,Supermarket Type2
freq,1,4885,1249,4676,6025,6262,4676

In [ ]:
# checking null and duplicate values

df.isnull().sum()
df.duplicated().sum()

Product_Id                   0
Product_Weight               0
Product_Sugar_Content        0
Product_Allocated_Area       0
Product_Type                 0
Product_MRP                  0
Store_Id                     0
Store_Establishment_Year     0
Store_Size                   0
Store_Location_City_Type     0
Store_Type                   0
Product_Store_Sales_Total    0
dtype: int64

np.int64(0)

In [ ]:
df["Store_Type"].unique()
df["Store_Type"].value_counts()
df["Product_Type"].unique()
df["Product_Type"].value_counts()
df["Store_Establishment_Year"].unique()
df["Store_Establishment_Year"].value_counts()

array(['Supermarket Type2', 'Departmental Store', 'Supermarket Type1',
       'Food Mart'], dtype=object)

Store_Type
Supermarket Type2     4676
Supermarket Type1     1586
Departmental Store    1349
Food Mart             1152
Name: count, dtype: int64

array(['Frozen Foods', 'Dairy', 'Canned', 'Baking Goods',
       'Health and Hygiene', 'Snack Foods', 'Meat', 'Household',
       'Hard Drinks', 'Fruits and Vegetables', 'Breads', 'Soft Drinks',
       'Breakfast', 'Others', 'Starchy Foods', 'Seafood'], dtype=object)

Product_Type
Fruits and Vegetables    1249
Snack Foods              1149
Frozen Foods              811
Dairy                     796
Household                 740
Baking Goods              716
Canned                    677
Health and Hygiene        628
Meat                      618
Soft Drinks               519
Breads                    200
Hard Drinks               186
Others                    151
Starchy Foods             141
Breakfast                 106
Seafood                    76
Name: count, dtype: int64

array([2009, 1999, 1987, 1998])

Store_Establishment_Year
2009    4676
1987    1586
1999    1349
1998    1152
Name: count, dtype: int64

In [ ]:
# correlation analysis
df.corr(numeric_only=True)

,Product_Weight,Product_Allocated_Area,Product_MRP,Store_Establishment_Year,Product_Store_Sales_Total
Product_Weight,1.000000,0.014754,0.532716,-0.161907,0.737955
Product_Allocated_Area,0.014754,1.000000,-0.009508,0.004467,-0.000933
Product_MRP,0.532716,-0.009508,1.000000,-0.189357,0.787989
Store_Establishment_Year,-0.161907,0.004467,-0.189357,1.000000,-0.185027
Product_Store_Sales_Total,0.737955,-0.000933,0.787989,-0.185027,1.000000

corelation noticed :-
1.
2.

In [ ]:
# target value discription
df["Product_Store_Sales_Total"].describe()

count    8763.000000
mean     3464.003640
std      1065.630494
min        33.000000
25%      2761.715000
50%      3452.340000
75%      4145.165000
max      8000.000000
Name: Product_Store_Sales_Total, dtype: float64

In [ ]:
df.groupby("Product_Type")["Product_Store_Sales_Total"].mean()
df.groupby("Store_Type")["Product_Store_Sales_Total"].mean()
df.groupby("Store_Location_City_Type")["Product_Store_Sales_Total"].mean()
df.groupby("Store_Size")["Product_Store_Sales_Total"].mean()
df.groupby("Product_MRP")["Product_Store_Sales_Total"].mean()
df.groupby("Store_Location_City_Type")["Product_MRP"].mean()
df.groupby("Store_Id")["Product_Store_Sales_Total"].mean()

Product_Type
Baking Goods             3425.958101
Breads                   3574.711200
Breakfast                3416.324623
Canned                   3397.463383
Dairy                    3532.560352
Frozen Foods             3464.834562
Fruits and Vegetables    3443.421353
Hard Drinks              3364.594731
Health and Hygiene       3445.393646
Household                3465.865095
Meat                     3445.326764
Others                   3586.068212
Seafood                  3584.263684
Snack Foods              3471.711880
Soft Drinks              3462.513911
Starchy Foods            3679.251418
Name: Product_Store_Sales_Total, dtype: float64

Store_Type
Departmental Store    4946.966323
Food Mart             1762.942465
Supermarket Type1     3923.778802
Supermarket Type2     3299.312111
Name: Product_Store_Sales_Total, dtype: float64

Store_Location_City_Type
Tier 1    4946.966323
Tier 2    3457.473109
Tier 3    1762.942465
Name: Product_Store_Sales_Total, dtype: float64

Store_Size
High      3923.778802
Medium    3668.222573
Small     1762.942465
Name: Product_Store_Sales_Total, dtype: float64

Product_MRP
31.00      253.53
41.84      166.92
50.13      180.86
50.42      203.55
51.90      836.23
           ...
247.62    6653.24
250.14    6083.39
250.57    6736.81
254.34    6231.41
266.00    8000.00
Name: Product_Store_Sales_Total, Length: 6100, dtype: float64

Store_Location_City_Type
Tier 1    181.358725
Tier 2    146.987597
Tier 3    107.080634
Name: Product_MRP, dtype: float64

Store_Id
OUT001    3923.778802
OUT002    1762.942465
OUT003    4946.966323
OUT004    3299.312111
Name: Product_Store_Sales_Total, dtype: float64

In [ ]:
df["Store_Age"] = 2026 - df["Store_Establishment_Year"]
df["Store_Age"].describe()
df.groupby("Store_Age")["Product_Store_Sales_Total"].mean()

count    8763.000000
mean       23.967249
std         8.388381
min        17.000000
25%        17.000000
50%        17.000000
75%        28.000000
max        39.000000
Name: Store_Age, dtype: float64

Store_Age
17    3299.312111
27    4946.966323
28    1762.942465
39    3923.778802
Name: Product_Store_Sales_Total, dtype: float64

In [ ]:
# extracting product category
df["Product_Category"] = df["Product_Id"].str[:2]
df["Product_Category"].describe()
df.groupby("Product_Category")["Product_Store_Sales_Total"].mean()

count     8763
unique       3
top         FD
freq      6539
Name: Product_Category, dtype: object

Product_Category
DR    3436.679915
FD    3465.707429
NC    3469.350678
Name: Product_Store_Sales_Total, dtype: float64

In [ ]:
# detecting outlier
Q1 = df["Product_MRP"].quantile(0.25)
Q3 = df["Product_MRP"].quantile(0.75)

IQR = Q3 - Q1

outliers = df[
    (df["Product_MRP"] < Q1 - 1.5*IQR) |
    (df["Product_MRP"] > Q3 + 1.5*IQR)
]
outliers.describe()
outliers.head()
outliers.info()

,Product_Weight,Product_Allocated_Area,Product_MRP,Store_Establishment_Year,Product_Store_Sales_Total,Store_Age
count,57.000000,57.000000,57.000000,57.00000,57.000000,57.00000
mean,13.176140,0.058842,155.600351,1998.54386,3725.306842,27.45614
std,4.248207,0.043909,92.433837,0.50250,2786.228494,0.50250
min,6.950000,0.009000,31.000000,1998.00000,166.920000,27.00000
25%,9.630000,0.027000,59.220000,1998.00000,836.230000,27.00000
50%,13.430000,0.042000,230.510000,1999.00000,5398.610000,27.00000
75%,16.750000,0.081000,238.810000,1999.00000,6250.670000,28.00000
max,22.000000,0.168000,266.000000,1999.00000,8000.000000,28.00000

,Product_Id,Product_Weight,Product_Sugar_Content,Product_Allocated_Area,Product_Type,Product_MRP,Store_Id,Store_Establishment_Year,Store_Size,Store_Location_City_Type,Store_Type,Product_Store_Sales_Total,Store_Age,Product_Category
21,NC177,16.75,No Sugar,0.043,Health and Hygiene,236.09,OUT003,1999,Medium,Tier 1,Departmental Store,6643.63,27,NC
88,FD1829,14.62,Low Sugar,0.038,Dairy,231.55,OUT003,1999,Medium,Tier 1,Departmental Store,5627.68,27,FD
285,FD3087,18.06,Low Sugar,0.057,Fruits and Vegetables,246.35,OUT003,1999,Medium,Tier 1,Departmental Store,6707.04,27,FD
428,FD442,16.59,Low Sugar,0.039,Dairy,232.41,OUT003,1999,Medium,Tier 1,Departmental Store,3724.32,27,FD
657,NC935,14.35,No Sugar,0.037,Household,241.63,OUT003,1999,Medium,Tier 1,Departmental Store,5772.44,27,NC

<class 'pandas.core.frame.DataFrame'>
Index: 57 entries, 21 to 8647
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Product_Id                 57 non-null     object
 1   Product_Weight             57 non-null     float64
 2   Product_Sugar_Content      57 non-null     object
 3   Product_Allocated_Area     57 non-null     float64
 4   Product_Type               57 non-null     object
 5   Product_MRP                57 non-null     float64
 6   Store_Id                   57 non-null     object
 7   Store_Establishment_Year   57 non-null     int64
 8   Store_Size                 57 non-null     object
 9   Store_Location_City_Type   57 non-null     object
 10  Store_Type                 57 non-null     object
 11  Product_Store_Sales_Total  57 non-null     float64
 12  Store_Age                  57 non-null     int64
 13  Product_Category           57 non-null     object
dtypes: float64(4), int64(2), object(8)
memory usage: 6.7+ KB

**OBSERVATIONS ON EDA :-**

1. Missing Value Analysis :-
The dataset contains no missing values across any of the features.

2. Correlation Analysis :-
Product Weight vs Sales → 0.73
Product MRP vs Sales → 0.78
This suggests that both product weight and product price are significant factors influencing sales.

3. Store Location Impact :-  
Higher-tier cities contribute to better sales performance.

4. Store Size Analysis :-
Stores with smaller sizes have comparatively lower average sales.

5. Store Age Analysis :-
No significant relationship was observed between store age and sales.

6. Outlier Detection :-
Using the IQR method, 57 outliers were identified in the dataset.

7. Probability of buying expensive item increase by tier of city